### ISSUE TITLE
Invalid wining combinations - tictac_game.py

### ISSUE THREAD

**Issue by github-suraj** [kaviadigdarshan/python_programs#1]
Combinations to check for winner is incorrect at line no 49
(3, 4, 6) -> (3, 4, 5) and (2, 6, 8) -> (2, 5, 8)

**Comment by kaviadigdarshan** [comment]
Good catch! Will correct.

**Comment by kaviadigdarshan** [comment]
Done 😁

https://github.com/kaviadigdarshan/python_programs/blob/3193241ea1e61bc1a0e3953a35d0b9dd049c4757/tictac_game.py#L49
