### ISSUE TITLE
Match tie check

### ISSUE THREAD

**Issue by github-suraj** [kaviadigdarshan/python_programs#2]
Check missing for match tie in case all the positions are filled up.

**Comment by kaviadigdarshan** [comment]
Fixed it. Also, added a replay option. Hope you like it 😃
Thanks for making the game better 🤝🏻

https://github.com/kaviadigdarshan/python/blob/6bfbd8bddc626a535c7e8cd63a0752ccde4c3cf7/tictac_game.py#L88-L95
